spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:9004/coupon_example
    username: root
    password: 1234

  data:
    redis:
      host: host.docker.internal
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    sql: debug
