version: '3.8'

services:
  local-db:
    image: mysql:8-oracle
    environment:
      MYSQL_DATABASE: coupon_example
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "9004:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"